spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/casa-do-codigo
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: none